### ISSUE TITLE
'onGenerateRoute: Router.generateRoute' in main.dart hase error. what should i do?

### ISSUE THREAD

**Issue by AmirHosseinYazdani** [obnil/flutter_music_app#12]

**Comment by seoeaa** [comment]
Rename Router to ModularRouter

**Comment by seoeaa** [comment]
visit me download corrected to stable version

**Comment by AmirHosseinYazdani** [comment]
I don't know how is that thread should work. But
Anyway, I fixed it by another solution.
Thanx ✌️👍

**Comment by Felixcity35** [comment]
am still having this error after renaming 'Router' to 'ModularRouter'  pls has any one fix this issues

**Comment by XeraFiu-YTB** [comment]
@Felixcity35 , rename Router by ModularRouter in main.dart and also in lib/config/router_manager.dart

**Comment by Felixcity35** [comment]
> @Felixcity35 , rename Router by ModularRouter in main.dart and also in lib/config/router_manager.dart

thank u it works
